import bcrypt from "bcryptjs";
import { pool } from "../config/db.js";
const password = await bcrypt.hash("DemoPass123!", 12);
async function user(email:string,role:"buyer"|"supplier"|"admin"){const r=await pool.query<{id:string}>("INSERT INTO users (email,password_hash,role) VALUES ($1,$2,$3) ON CONFLICT(email) DO UPDATE SET password_hash=EXCLUDED.password_hash RETURNING id",[email,password,role]);return r.rows[0].id;}
try { const admin=await user("admin@threadmark.demo","admin"), buyer=await user("buyer@northstar.demo","buyer"), malabar=await user("hello@malabarweaves.demo","supplier"), coastal=await user("hello@coastaltextiles.demo","supplier"), erode=await user("hello@erodeloomhouse.demo","supplier");
await pool.query(`INSERT INTO buyer_profiles (user_id,business_type,industry,product_categories_interest,preferred_fabric_types,typical_order_quantity,budget_range,additional_preferences) VALUES ($1,'Uniform manufacturer','Institutional apparel',ARRAY['Uniforms','Apparel'],ARRAY['Cotton twill','Recycled canvas'],'250–500 metres','₹200–₹450/m','Needs documented certifications') ON CONFLICT(user_id) DO NOTHING`,[buyer]);
for(const [id,name,type,cats,fabrics,moq,verified] of [[malabar,"Malabar Weaves","Mill",["Apparel","Uniforms"],["Cotton twill","Poplin"],50,"verified"],[coastal,"Coastal Technical Textiles","Manufacturer",["Outdoor","Technical"],["Recycled polyester","Canvas"],100,"verified"],[erode,"Erode Loom House","Weaver",["Home textiles","Apparel"],["Linen blend","Herringbone"],40,"unverified"]] as const) await pool.query(`INSERT INTO supplier_profiles (user_id,business_name,business_type,contact_info,business_address,operating_hours,product_categories,fabric_types_offered,moq,status,verification_documents,verification_status) VALUES ($1,$2,$3,'{}','Private','Private',$4,$5,$6,'approved','[]',$7::verification_status) ON CONFLICT(user_id) DO UPDATE SET status='approved',verification_status=$7::verification_status`,[id,name,type,cats,fabrics,moq,verified]);
function swatch(name:string,hex:string):string{const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="700"><rect width="900" height="700" fill="${hex}"/><rect x="30" y="30" width="840" height="640" fill="none" stroke="#2B241C" stroke-opacity="0.15" stroke-width="2"/><text x="50%" y="50%" text-anchor="middle" dominant-baseline="middle" font-family="Georgia, serif" font-size="42" fill="#2B241C" fill-opacity="0.55">${name}</text></svg>`;return `data:image/svg+xml;base64,${Buffer.from(svg).toString("base64")}`;}
const catalog=[
  [malabar,"Organic Cotton Twill","Apparel","100% organic cotton",280,245,"ready_stock",900,["GOTS","OEKO-TEX"],["organic"],swatch("Organic Cotton Twill","#D9CBAE")],
  [coastal,"Recycled Polyester Canvas","Outdoor","100% recycled polyester",340,310,"made_to_order",1200,["GRS"],["recycled"],swatch("Recycled Polyester Canvas","#8C9B8A")],
  [erode,"Linen Cotton Herringbone","Home textiles","55% linen / 45% cotton",220,385,"ready_stock",530,["OEKO-TEX"],[],swatch("Linen Cotton Herringbone","#C9B79C")],
  [erode,"Deadstock Viscose Satin","Fashion","100% viscose",150,190,"ready_stock",300,[],["deadstock"],swatch("Deadstock Viscose Satin","#A8452F")],
  [coastal,"Merino Wool Flannel","Apparel","100% merino wool",320,540,"made_to_order",400,["RWS"],[],swatch("Merino Wool Flannel","#5B5347")],
  [coastal,"Technical Ripstop Nylon","Technical","100% nylon",180,275,"ready_stock",700,["bluesign"],[],swatch("Technical Ripstop Nylon","#3E4C5E")],
  [malabar,"Uniform Poly-Cotton Blend","Uniforms","65% polyester / 35% cotton",210,165,"ready_stock",1500,["OEKO-TEX"],[],swatch("Uniform Poly-Cotton Blend","#29335C")],
  [erode,"Organic Hemp Canvas","Home textiles","100% hemp",400,420,"made_to_order",250,["GOTS"],["organic"],swatch("Organic Hemp Canvas","#7C6A45")],
  [malabar,"Denim Selvedge Twill","Apparel","100% cotton denim",380,460,"ready_stock",600,[],[],swatch("Denim Selvedge Twill","#29335C")]
] as const;
await pool.query("DELETE FROM order_status_history WHERE order_id IN (SELECT order_id FROM order_items WHERE product_id IN (SELECT id FROM products WHERE supplier_id IN ($1,$2,$3)))",[malabar,coastal,erode]);
await pool.query("DELETE FROM order_items WHERE product_id IN (SELECT id FROM products WHERE supplier_id IN ($1,$2,$3))",[malabar,coastal,erode]);
await pool.query("DELETE FROM orders WHERE buyer_id=$1",[buyer]);
await pool.query("DELETE FROM comparison_events WHERE buyer_id=$1",[buyer]);
await pool.query("DELETE FROM sample_requests WHERE product_id IN (SELECT id FROM products WHERE supplier_id IN ($1,$2,$3))",[malabar,coastal,erode]);
await pool.query("DELETE FROM rfq_requests WHERE product_id IN (SELECT id FROM products WHERE supplier_id IN ($1,$2,$3))",[malabar,coastal,erode]);
await pool.query("DELETE FROM cart_items WHERE product_id IN (SELECT id FROM products WHERE supplier_id IN ($1,$2,$3))",[malabar,coastal,erode]);
await pool.query("DELETE FROM product_views WHERE product_id IN (SELECT id FROM products WHERE supplier_id IN ($1,$2,$3))",[malabar,coastal,erode]);
await pool.query("DELETE FROM price_tiers WHERE product_id IN (SELECT id FROM products WHERE supplier_id IN ($1,$2,$3))",[malabar,coastal,erode]);
await pool.query("DELETE FROM products WHERE supplier_id IN ($1,$2,$3)",[malabar,coastal,erode]);
const products:string[]=[];
for(const [supplier,name,category,composition,gsm,price,stockType,stock,certs,tags,image] of catalog){const r=await pool.query<{id:string}>(`INSERT INTO products (supplier_id,name,category,description,colors,specifications,gsm,composition,weave_type,width,shrinkage_rate,colorfastness_rating,stock_qty,stock_type,lead_time_days,certifications,price,images,status,sustainability_tags) VALUES ($1,$2,$3,'Documented demo fabric lot for B2B textile sourcing.',ARRAY['Natural','Indigo'], '{}'::jsonb,$4,$5,'Twill','150 cm','≤ 3%','Grade 4–5',$6,$7::stock_type,CASE WHEN $7='made_to_order' THEN 14 ELSE 3 END,$8,$9,ARRAY[$10],'available',$11) ON CONFLICT DO NOTHING RETURNING id`,[supplier,name,category,gsm,composition,stock,stockType,certs,price,image,tags]); const id=r.rows[0]?.id??(await pool.query<{id:string}>("SELECT id FROM products WHERE supplier_id=$1 AND name=$2",[supplier,name])).rows[0].id;products.push(id);await pool.query("INSERT INTO price_tiers (product_id,min_qty,price_per_unit) VALUES ($1,50,$2),($1,250,$3),($1,500,$4) ON CONFLICT(product_id,min_qty) DO NOTHING",[id,price,Number(price)*.95,Number(price)*.89]);}
for(let i=0;i<36;i++)await pool.query("INSERT INTO product_views (buyer_id,product_id,timestamp) VALUES ($1,$2,now()-($3||' days')::interval)",[buyer,products[i%products.length],String(2+i*3)]);
for(const ids of [[products[0],products[1]],[products[0],products[2]],[products[0],products[1]]])await pool.query("INSERT INTO comparison_events (buyer_id,product_ids,timestamp) VALUES ($1,$2,now()-($3||' days')::interval)",[buyer,ids,String(8+Math.floor(Math.random()*75))]);
for(const days of [126,84,42]){const order=await pool.query<{id:string}>("INSERT INTO orders (buyer_id,shipping_info,status,total,created_at) VALUES ($1,'{}','completed',61250,now()-($2||' days')::interval) RETURNING id",[buyer,String(days)]);await pool.query("INSERT INTO order_items (order_id,product_id,supplier_id,quantity,price_at_order) VALUES ($1,$2,$3,250,245)",[order.rows[0].id,products[0],malabar]);for(const [status,offset] of [["pending",5],["accepted",4],["preparing",3],["ready_for_dispatch",2],["completed",1]] as [string,number][])await pool.query("INSERT INTO order_status_history (order_id,status,updated_at) VALUES ($1,$2,now()-(($3)::text||' days')::interval)",[order.rows[0].id,status,days-offset]);}
console.log("Demo seed complete. Accounts use DemoPass123!: buyer@northstar.demo, hello@malabarweaves.demo, hello@coastaltextiles.demo, hello@erodeloomhouse.demo, admin@threadmark.demo");
} finally { await pool.end(); }
