"use client";
import Link from "next/link";
import { useState } from "react";
import { z } from "zod";
import { api } from "@/lib/api";
import { useAuthStore, type SessionUser } from "@/stores/auth-store";
const formSchema = z.object({ email: z.string().trim().toLowerCase().email("Enter a valid email address"), password: z.string().min(8, "Use at least 8 characters").max(128), role: z.enum(["buyer", "supplier"]).optional(), username: z.string().min(3).max(30).regex(/^[a-zA-Z0-9_]+$/, "Letters, numbers, and underscores only").optional() });
type Mode = "login" | "register";
export function AuthForm({ mode }: { mode: Mode }) { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState<"buyer" | "supplier">("buyer"); const [username, setUsername] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const setUser = useAuthStore((state) => state.setUser);
  const isRegister = mode === "register";
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); const parsed = formSchema.safeParse({ email, password, ...(isRegister ? { role } : {}), ...(isRegister && role === 'buyer' ? { username } : {}) }); if (!parsed.success) { setError(parsed.error.issues[0].message); return; } setBusy(true); try { const result = await api<{ user: SessionUser }>(`/auth/${isRegister ? "register" : "login"}`, { method: "POST", body: JSON.stringify(parsed.data) }); setUser(result.user); const destination = isRegister ? `/onboarding/${result.user.role}` : (result.user.role === "buyer" ? "/buyer" : `/${result.user.role}`); window.location.assign(destination); } catch (cause) { setError(cause instanceof Error ? cause.message : "Something went wrong. Please try again."); } finally { setBusy(false); } }
  return <form onSubmit={submit} className="space-y-5" noValidate><div><label htmlFor="email" className="mb-1.5 block text-sm font-semibold">Work email</label><input id="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} className="w-full rounded-sm border border-loom bg-[#f7f1e7] px-3 py-2.5" placeholder="you@company.com" required /></div><div><label htmlFor="password" className="mb-1.5 block text-sm font-semibold">Password</label><input id="password" type="password" autoComplete={isRegister ? "new-password" : "current-password"} value={password} onChange={(event) => setPassword(event.target.value)} className="w-full rounded-sm border border-loom bg-[#f7f1e7] px-3 py-2.5" placeholder="At least 8 characters" required /></div>{isRegister && <fieldset><legend className="mb-2 text-sm font-semibold">I am joining as a</legend><div className="grid grid-cols-2 gap-3">{(["buyer", "supplier"] as const).map((item) => <label key={item} className={`cursor-pointer rounded-sm border p-3 ${role === item ? "border-indigo-dye bg-indigo-dye/10" : "border-loom bg-[#f7f1e7]"}`}><input className="sr-only" type="radio" checked={role === item} onChange={() => setRole(item)} /><span className="block font-semibold capitalize">{item}</span><span className="mt-1 block text-xs">{item === "buyer" ? "Source fabrics for your business" : "Manage products and orders"}</span></label>)}</div></fieldset>}{isRegister && role === "buyer" && <div><label htmlFor="username" className="mb-1.5 block text-sm font-semibold">Username</label><input id="username" value={username} onChange={(event) => setUsername(event.target.value)} className="w-full rounded-sm border border-loom bg-[#f7f1e7] px-3 py-2.5" placeholder="e.g. fashionista_99" required /></div>}{error && <p role="alert" className="rounded-sm border border-danger/40 bg-danger/10 p-3 text-sm text-danger">{error}</p>}<button disabled={busy} className="w-full rounded-sm bg-indigo-dye px-4 py-3 font-semibold text-cotton disabled:cursor-wait disabled:opacity-70">{busy ? "Please wait…" : isRegister ? "Create account" : "Sign in"}</button><p className="text-center text-sm">{isRegister ? "Already have an account?" : "New to ThreadMark?"} <Link className="font-semibold text-indigo-dye underline" href={isRegister ? "/login" : "/register"}>{isRegister ? "Sign in" : "Create an account"}</Link></p></form>; }
