"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {api} from "@/lib/api";
import {buyerProfileSchema,supplierProfileSchema} from "@threadmark/shared";
declare global { interface Window { webkitSpeechRecognition?: new()=>SpeechRecognition; SpeechRecognition?: new()=>SpeechRecognition; } } interface SpeechRecognition extends EventTarget { continuous:boolean; interimResults:boolean; lang:string; start():void; onresult:(event:{results:{[index:number]:{[index:number]:{transcript:string}}}})=>void; onerror:()=>void; }
type Kind="buyer"|"supplier";const buyerQuestions=[['businessType','What type of business do you run?'],['industry','Which industry do you serve?'],['productCategoriesInterest','Which product categories interest you? Separate choices with commas.'],['preferredFabricTypes','Which fabric types do you prefer? Separate choices with commas.'],['typicalOrderQuantity','What is your typical order quantity? (e.g. 100-500)'],['budgetRange','What is your usual budget range per metre? (e.g. 50-100)'],['additionalPreferences','Any additional sourcing preferences?']];const supplierQuestions=[['businessName','What is your business name?'],['businessType','What type of business is it?'],['contactEmail','What is your business contact email?'],['contactPhone','What is your business contact phone?'],['businessAddress','What is your business address?'],['operatingHours','What are your operating hours? (e.g. 9 AM - 5 PM)'],['productCategories','Which product categories do you offer? Separate choices with commas.'],['fabricTypesOffered','Which fabric types do you offer? Separate choices with commas.'],['moq','What is your minimum order quantity?']];
const validators:Record<string,(v:string)=>string|null>={contactEmail:v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.trim())?null:"That doesn't look like a valid email address.",contactPhone:v=>/^\+?[0-9\s\-()]+$/.test(v.trim())&&v.replace(/\D/g,'').length>=7?null:"Enter a valid phone number (at least 7 digits).",moq:v=>Number.isFinite(Number(v.trim()))&&Number(v.trim())>0?null:"Enter a number greater than 0.",typicalOrderQuantity:v=>/^[\d\s\-,]+$/.test(v)?null:"Enter numbers and hyphens only (e.g. 100-500)",budgetRange:v=>/^[\d\s\-.,$₹€£]+$/.test(v)?null:"Enter a numeric budget range (e.g. 50-100)",operatingHours:v=>/\d/.test(v)?null:"Enter valid operating hours (e.g. 9 AM - 5 PM)"};
export function OnboardingChat({kind}:{kind:Kind}){const questions=kind==='buyer'?buyerQuestions:supplierQuestions;const [index,setIndex]=useState(0);const [answer,setAnswer]=useState("");const [answers,setAnswers]=useState<Record<string,string>>({});const [error,setError]=useState("");const [voiceError,setVoiceError]=useState("");const [saving,setSaving]=useState(false);const router=useRouter();const question=questions[index];
const [questionText,setQuestionText]=useState(question[1]);const [questionLoading,setQuestionLoading]=useState(true);
useEffect(()=>{
  let cancelled=false;
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setQuestionLoading(true);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setQuestionText(question[1]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setError("");
  api<{data:{question:string}}>("/ai/onboarding-prompt",{method:"POST",body:JSON.stringify({kind,fieldLabel:question[1],priorAnswers:answers})}).then(r=>{if(!cancelled&&r.data.question)setQuestionText(r.data.question)}).catch(()=>{}).finally(()=>{if(!cancelled)setQuestionLoading(false)});return ()=>{cancelled=true};
// eslint-disable-next-line react-hooks/exhaustive-deps
},[index]);
function listen(){const Recognition=window.SpeechRecognition??window.webkitSpeechRecognition;if(!Recognition){setVoiceError("Voice input is not supported in this browser. Type your response instead.");return;}const recognition=new Recognition();recognition.lang="en-IN";recognition.continuous=false;recognition.interimResults=false;recognition.onresult=(event)=>setAnswer(event.results[0][0].transcript);recognition.onerror=()=>setVoiceError("I could not hear that. Try speaking again or type your response.");recognition.start();}
function goBack(){if(index===0)return;const prevKey=questions[index-1][0];setAnswer(answers[prevKey]??"");setError("");setIndex(index-1);}
async function next(e:React.FormEvent){e.preventDefault();if(!answer.trim())return;const validator=validators[question[0]];const validationError=validator?validator(answer):null;if(validationError){setError(validationError);return;}const data={...answers,[question[0]]:answer.trim()};setAnswers(data);setError("");if(index<questions.length-1){const nextKey=questions[index+1][0];setAnswer(data[nextKey]??"");setIndex(index+1);return;}setSaving(true);try{const payload=kind==='buyer'?{businessType:data.businessType,industry:data.industry,productCategoriesInterest:data.productCategoriesInterest.split(',').map(v=>v.trim()).filter(Boolean),preferredFabricTypes:data.preferredFabricTypes.split(',').map(v=>v.trim()).filter(Boolean),typicalOrderQuantity:data.typicalOrderQuantity,budgetRange:data.budgetRange,additionalPreferences:data.additionalPreferences}:{businessName:data.businessName,businessType:data.businessType,contactInfo:{email:data.contactEmail,phone:data.contactPhone},businessAddress:data.businessAddress,operatingHours:data.operatingHours,productCategories:data.productCategories.split(',').map(v=>v.trim()).filter(Boolean),fabricTypesOffered:data.fabricTypesOffered.split(',').map(v=>v.trim()).filter(Boolean),moq:Number(data.moq)};const validation=(kind==='buyer'?buyerProfileSchema:supplierProfileSchema).safeParse(payload);if(!validation.success){const issue=validation.error.issues[0];setError(issue?`${issue.path.join('.')}: ${issue.message}`:'Check your onboarding answers.');setSaving(false);return;}await api(kind==='buyer'?'/profiles/buyer':'/profiles/supplier',{method:'PUT',body:JSON.stringify(validation.data)});router.push(kind==='buyer'?'/buyer':'/supplier');}catch(cause){setError(cause instanceof Error?cause.message:'Your profile could not be saved. Check your answers and try again.');}finally{setSaving(false);}}
return <main className="woven-grid grid min-h-screen place-items-center p-5"><section className="swatch-tag w-full max-w-2xl border border-loom bg-cotton p-7 shadow-[8px_8px_0_#29335C] sm:p-10"><p className="font-data text-xs uppercase tracking-[.15em] text-ochre">{kind} onboarding · {index+1} of {questions.length}</p><h1 className="mt-3 font-display text-4xl">Let&apos;s set up your {kind==='buyer'?'sourcing desk':'trade profile'}.</h1><div className="mt-8 space-y-5"><div className="swatch-tag max-w-[86%] border border-loom bg-[#f7f1e7] p-4 leading-7">{questionLoading?"…":questionText}</div><form onSubmit={next}><label className="sr-only" htmlFor="answer">Your answer</label><div className="flex gap-2"><textarea id="answer" autoFocus value={answer} onChange={e=>setAnswer(e.target.value)} className="min-h-24 w-full border border-loom bg-[#f7f1e7] p-3" placeholder="Type your answer…"/><button type="button" onClick={listen} className="border border-indigo-dye px-3 text-sm font-semibold text-indigo-dye">Speak</button></div>{voiceError&&<p role="alert" className="mt-2 text-xs text-danger">{voiceError}</p>}<div className="mt-3 flex justify-between"><button type="button" onClick={goBack} disabled={index===0} className="border border-loom px-4 py-2.5 text-sm font-semibold disabled:opacity-40">&larr; Back</button><button disabled={saving} className="rounded-sm bg-indigo-dye px-5 py-3 font-semibold text-cotton disabled:opacity-70">{saving?'Saving your profile…':index===questions.length-1?'Finish setup':'Continue'}</button></div></form>{error&&<p role="alert" className="border border-danger/40 bg-danger/10 p-3 text-sm text-danger">{error}</p>}</div></section></main>}
