import { env } from "../config/env.js";
const PIPELINE_BASE = "https://router.huggingface.co/hf-inference/models";
const CHAT_BASE = "https://router.huggingface.co/v1";
const embeddingCache = new Map<string, number[]>();
const pause = (ms:number) => new Promise(resolve => setTimeout(resolve, ms));

async function hfPipeline(path: string, body: unknown) { if (!env.HF_API_TOKEN) throw new Error("Hugging Face API token is not configured"); let last: Response | undefined; for (let attempt=0;attempt<3;attempt++) { const response = await fetch(`${PIPELINE_BASE}/${path}`, { method:"POST", headers:{ Authorization:`Bearer ${env.HF_API_TOKEN}`, "Content-Type":"application/json" }, body:JSON.stringify(body) }); if (response.status !== 429 && response.status !== 503) { if (!response.ok) throw new Error(`Hugging Face request failed (${response.status})`); return response.json(); } last=response; await pause(500 * 2 ** attempt); } throw new Error(`Hugging Face rate limit persisted (${last?.status ?? "unknown"})`); }

async function hfChat(body: unknown) { if (!env.HF_API_TOKEN) throw new Error("Hugging Face API token is not configured"); let last: Response | undefined; for (let attempt=0;attempt<6;attempt++) { const response = await fetch(`${CHAT_BASE}/chat/completions`, { method:"POST", headers:{ Authorization:`Bearer ${env.HF_API_TOKEN}`, "Content-Type":"application/json" }, body:JSON.stringify(body) }); if (response.status !== 429 && response.status !== 503) { if (!response.ok) { const errBody = await response.text().catch(() => "(unreadable)"); throw new Error(`Hugging Face request failed (${response.status}): ${errBody}`); } return response.json(); } last=response; await pause(2000 * (attempt+1)); } throw new Error(`Hugging Face rate limit persisted (${last?.status ?? "unknown"})`); }

export async function embed(text:string) { const cacheKey=text.trim().toLowerCase(); const cached=embeddingCache.get(cacheKey); if(cached) return cached; const result=await hfPipeline(`${env.HF_EMBEDDING_MODEL}/pipeline/feature-extraction`,{inputs:text,options:{wait_for_model:true}}); const vector=Array.isArray(result?.[0]) ? result[0] : result; if(!Array.isArray(vector)) throw new Error("Embedding model returned an invalid response"); embeddingCache.set(cacheKey,vector); return vector as number[]; }
export async function converse(system:string, messages:{role:"user"|"assistant";content:string}[]) { return hfChat({model:`${env.HF_CHAT_MODEL}:novita`,messages:[{role:"system",content:system},...messages],max_tokens:500,temperature:0.2}); }
export async function warmModel() { if(!env.HF_API_TOKEN) return { warmed:false, reason:"HF_API_TOKEN is not configured" }; try { await converse("Reply only with ready.",[{role:"user",content:"warm"}]); return {warmed:true}; } catch (error) { return {warmed:false,reason:error instanceof Error?error.message:"Unknown warm-up failure"}; } }
