import type {NextFunction,Request,Response} from "express";
import {z} from "zod";
import {query} from "../config/db.js";
import {HttpError} from "../utils/http-error.js";
export async function overview(_req:Request,res:Response,next:NextFunction){try{const [buyers,suppliers,products,orders,gmv,activity]=await Promise.all([query<{count:string}>("SELECT count(*) FROM users WHERE role='buyer'"),query<{count:string}>("SELECT count(*) FROM users WHERE role='supplier'"),query<{count:string}>("SELECT count(*) FROM products"),query<{count:string}>("SELECT count(*) FROM orders"),query<{total:string}>("SELECT COALESCE(sum(total),0) total FROM orders"),query(`SELECT 'order' AS type,id,created_at AS timestamp FROM orders UNION ALL SELECT 'rfq' AS type,id,created_at AS timestamp FROM rfq_requests ORDER BY timestamp DESC LIMIT 12`)]);res.json({data:{totalBuyers:Number(buyers.rows[0].count),totalSuppliers:Number(suppliers.rows[0].count),totalProducts:Number(products.rows[0].count),totalOrders:Number(orders.rows[0].count),mockGmv:gmv.rows[0].total,activity:activity.rows}});}catch(error){next(error)}}
export async function suppliers(req:Request,res:Response,next:NextFunction){try{const term=typeof req.query.search==='string'?req.query.search.trim():"";const result=await query(`SELECT u.id,u.email,u.created_at,sp.business_name,sp.business_type,sp.product_categories,sp.fabric_types_offered,sp.moq,sp.status,sp.verification_documents,sp.verification_status FROM users u JOIN supplier_profiles sp ON sp.user_id=u.id WHERE u.role='supplier' AND ($1='' OR sp.business_name ILIKE '%'||$1||'%' OR u.email ILIKE '%'||$1||'%') ORDER BY u.created_at DESC`,[term]);res.json({data:result.rows});}catch(error){next(error)}}
export async function setSupplierStatus(req:Request,res:Response,next:NextFunction){try{const input=z.object({status:z.enum(["approved","suspended","pending"])}).parse(req.body);const result=await query("UPDATE supplier_profiles SET status=$1 WHERE user_id=$2 RETURNING user_id,status",[input.status,String(req.params.id)]);if(!result.rows[0])throw new HttpError(404,"Supplier not found");res.json({data:result.rows[0]});}catch(error){next(error)}}
export async function setVerification(req:Request,res:Response,next:NextFunction){try{const input=z.object({status:z.enum(["verified","unverified"])}).parse(req.body);const result=await query("UPDATE supplier_profiles SET verification_status=$1 WHERE user_id=$2 RETURNING user_id,verification_status",[input.status,String(req.params.id)]);if(!result.rows[0])throw new HttpError(404,"Supplier not found");res.json({data:result.rows[0]});}catch(error){next(error)}}
export async function buyers(req:Request,res:Response,next:NextFunction){try{const term=typeof req.query.search==='string'?req.query.search.trim():"";const result=await query(`SELECT u.id,u.email,u.created_at,b.business_type,b.industry,b.product_categories_interest,b.preferred_fabric_types,(SELECT count(*) FROM orders o WHERE o.buyer_id=u.id) AS order_count,(SELECT max(timestamp) FROM product_views pv WHERE pv.buyer_id=u.id) AS last_activity FROM users u LEFT JOIN buyer_profiles b ON b.user_id=u.id WHERE u.role='buyer' AND ($1='' OR u.email ILIKE '%'||$1||'%') ORDER BY u.created_at DESC`,[term]);res.json({data:result.rows});}catch(error){next(error)}}
export async function orders(_req:Request,res:Response,next:NextFunction){try{const result=await query(`SELECT o.id,o.status,o.total,o.created_at,b.email AS buyer_email,COALESCE(json_agg(json_build_object('product_id',i.product_id,'supplier_id',i.supplier_id,'quantity',i.quantity,'price',i.price_at_order)) FILTER(WHERE i.id IS NOT NULL),'[]') items FROM orders o JOIN users b ON b.id=o.buyer_id LEFT JOIN order_items i ON i.order_id=o.id GROUP BY o.id,b.email ORDER BY o.created_at DESC`);res.json({data:result.rows});}catch(error){next(error)}}
export async function moderateProduct(req:Request,res:Response,next:NextFunction){try{const input=z.object({status:z.enum(["flagged","removed","available"])}).parse(req.body);const result=await query("UPDATE products SET status=$1 WHERE id=$2 RETURNING id,status",[input.status,String(req.params.id)]);if(!result.rows[0])throw new HttpError(404,"Product not found");res.json({data:result.rows[0]});}catch(error){next(error)}}
export async function analytics(_req:Request,res:Response,next:NextFunction){try{const [demand,views,comparisons]=await Promise.all([query(`SELECT p.category,count(DISTINCT oi.order_id) AS order_count,sum(oi.quantity) AS quantity FROM products p JOIN order_items oi ON oi.product_id=p.id GROUP BY p.category ORDER BY quantity DESC`),query(`SELECT p.id,p.name,count(v.id) AS views FROM products p LEFT JOIN product_views v ON v.product_id=p.id GROUP BY p.id,p.name ORDER BY views DESC LIMIT 10`),query(`SELECT unnest(product_ids) AS product_id,count(*) AS comparisons FROM comparison_events GROUP BY product_id ORDER BY comparisons DESC LIMIT 10`)]);res.json({data:{categoryDemand:demand.rows,mostViewed:views.rows,mostCompared:comparisons.rows}});}catch(error){next(error)}}
export async function products(_req:Request,res:Response,next:NextFunction){try{const result=await query(`SELECT p.id,p.name,p.category,p.status,p.stock_qty,p.price,sp.business_name FROM products p JOIN supplier_profiles sp ON sp.user_id=p.supplier_id ORDER BY p.id DESC`);res.json({data:result.rows});}catch(error){next(error)}}
