import type { NextFunction, Request, Response } from "express";
import { z } from "zod";
import { shippingInfoSchema } from "@threadmark/shared";
import { query, transaction } from "../config/db.js";
import { HttpError } from "../utils/http-error.js";

const itemSchema = z.object({ productId: z.string().uuid(), quantity: z.coerce.number().int().min(1).max(100000) });
const updateSchema = z.object({ quantity: z.coerce.number().int().min(1).max(100000) });
async function cartIdFor(buyerId: string) { const result = await query<{ id: string }>("INSERT INTO carts (buyer_id) VALUES ($1) ON CONFLICT (buyer_id) DO UPDATE SET updated_at = now() RETURNING id", [buyerId]); return result.rows[0].id; }
export async function getCart(req: Request, res: Response, next: NextFunction) { try { const cartId = await cartIdFor(req.auth!.userId); const items = await query(`SELECT ci.id, ci.product_id, ci.quantity, p.name, COALESCE((SELECT pt.price_per_unit FROM price_tiers pt WHERE pt.product_id = p.id AND pt.min_qty <= ci.quantity ORDER BY pt.min_qty DESC LIMIT 1), p.price) AS price, p.price AS base_price, p.images, p.stock_qty, p.stock_type, p.status, sp.business_name, COALESCE(sp.moq, 1) AS moq FROM cart_items ci JOIN products p ON p.id = ci.product_id JOIN supplier_profiles sp ON sp.user_id = p.supplier_id WHERE ci.cart_id = $1 AND p.status = 'available' AND sp.status = 'approved' ORDER BY ci.id`, [cartId]); const total = items.rows.reduce((sum, item: any) => sum + Number(item.price) * item.quantity, 0); res.json({ data: { items: items.rows, total } }); } catch (error) { next(error); } }
export async function addCartItem(req: Request, res: Response, next: NextFunction) { try { const input = itemSchema.parse(req.body); const product = await query<{ id: string; stock_qty: number; moq: number }>("SELECT p.id, p.stock_qty, COALESCE(sp.moq, 1) AS moq FROM products p JOIN supplier_profiles sp ON p.supplier_id = sp.user_id WHERE p.id = $1 AND p.status = 'available' AND sp.status = 'approved'", [input.productId]); if (!product.rows[0]) throw new HttpError(404, "This product is not available in the marketplace"); const cartId = await cartIdFor(req.auth!.userId); const existing = await query<{ quantity: number }>("SELECT quantity FROM cart_items WHERE cart_id = $1 AND product_id = $2", [cartId, input.productId]); const currentQty = existing.rows[0]?.quantity || 0; const newQty = currentQty + input.quantity; if (newQty > product.rows[0].stock_qty) { throw new HttpError(409, `Only ${product.rows[0].stock_qty} units are available`); } if (newQty < product.rows[0].moq) { throw new HttpError(409, `This supplier requires a minimum order of ${product.rows[0].moq} units`); } const updated = await query(`INSERT INTO cart_items (cart_id, product_id, quantity) VALUES ($1, $2, $3) ON CONFLICT (cart_id, product_id) DO UPDATE SET quantity = $4 RETURNING quantity`, [cartId, input.productId, input.quantity, newQty]); res.status(201).json({ data: { productId: input.productId, quantity: updated.rows[0].quantity } }); } catch (error) { next(error); } }
export async function updateCartItem(req: Request, res: Response, next: NextFunction) { try { const input = updateSchema.parse(req.body); const product = await query<{ stock_qty: number; moq: number }>(`SELECT p.stock_qty, COALESCE(sp.moq, 1) AS moq FROM cart_items ci JOIN products p ON ci.product_id = p.id JOIN supplier_profiles sp ON p.supplier_id = sp.user_id WHERE ci.id = $1 AND ci.cart_id IN (SELECT id FROM carts WHERE buyer_id = $2)`, [req.params.itemId, req.auth!.userId]); if (!product.rows[0]) throw new HttpError(404, "Cart item not found"); if (input.quantity > product.rows[0].stock_qty) throw new HttpError(409, `Only ${product.rows[0].stock_qty} units are available`); if (input.quantity < product.rows[0].moq) throw new HttpError(409, `Minimum order is ${product.rows[0].moq} units`); const result = await query(`UPDATE cart_items SET quantity = $1 WHERE id = $2 RETURNING id, quantity`, [input.quantity, req.params.itemId]); res.json({ data: result.rows[0] }); } catch (error) { next(error); } }
export async function removeCartItem(req: Request, res: Response, next: NextFunction) { try { const result = await query("DELETE FROM cart_items WHERE id = $1 AND cart_id IN (SELECT id FROM carts WHERE buyer_id = $2) RETURNING id", [req.params.itemId, req.auth!.userId]); if (!result.rows[0]) throw new HttpError(404, "This cart item was not found"); res.status(204).send(); } catch (error) { next(error); } }
export async function checkout(req: Request, res: Response, next: NextFunction) { try { const shipping = shippingInfoSchema.parse(req.body.shippingInfo); const order = await transaction(async (client) => { const cart = await client.query<{ id: string }>("SELECT id FROM carts WHERE buyer_id = $1 FOR UPDATE", [req.auth!.userId]); if (!cart.rows[0]) throw new HttpError(400, "Your cart is empty"); const cartItems = await client.query<any>(`SELECT ci.product_id, ci.quantity, p.supplier_id, COALESCE((SELECT pt.price_per_unit FROM price_tiers pt WHERE pt.product_id = p.id AND pt.min_qty <= ci.quantity ORDER BY pt.min_qty DESC LIMIT 1), p.price) AS price, p.stock_qty, p.name, COALESCE(sp.moq, 1) AS moq FROM cart_items ci JOIN products p ON p.id = ci.product_id JOIN supplier_profiles sp ON sp.user_id = p.supplier_id WHERE ci.cart_id = $1 AND p.status = 'available' AND sp.status = 'approved' FOR UPDATE OF p`, [cart.rows[0].id]); if (!cartItems.rows.length) throw new HttpError(400, "Your cart is empty"); for (const item of cartItems.rows) { if (item.quantity > item.stock_qty) throw new HttpError(409, `${item.name} no longer has enough available stock`); if (item.quantity < item.moq) throw new HttpError(409, `${item.name} requires a minimum order of ${item.moq} units`); } const bySupplier = new Map<string, typeof cartItems.rows>();
for (const item of cartItems.rows) { const list = bySupplier.get(item.supplier_id) ?? []; list.push(item); bySupplier.set(item.supplier_id, list); }
const createdOrders: { id: string; total: number; order_number: string }[] = [];
for (const [_supplierId, items] of bySupplier) {
  const supplierTotal = items.reduce((sum, item) => sum + Number(item.price) * item.quantity, 0);
  const created = await client.query<{ id: string; order_number: string }>("INSERT INTO orders (buyer_id, shipping_info, total, status) VALUES ($1, $2, $3, 'pending') RETURNING id, order_number", [req.auth!.userId, shipping, supplierTotal]);
  for (const item of items) {
    await client.query("INSERT INTO order_items (order_id, product_id, supplier_id, quantity, price_at_order) VALUES ($1, $2, $3, $4, $5)", [created.rows[0].id, item.product_id, item.supplier_id, item.quantity, item.price]);
    await client.query("UPDATE products SET stock_qty = stock_qty - $1, status = CASE WHEN stock_qty - $1 = 0 THEN 'out_of_stock'::product_status ELSE status END WHERE id = $2", [item.quantity, item.product_id]);
  }
  await client.query("INSERT INTO order_status_history (order_id, status) VALUES ($1, 'pending')", [created.rows[0].id]);
  createdOrders.push({ id: created.rows[0].id, total: supplierTotal, order_number: created.rows[0].order_number });
}
await client.query("DELETE FROM cart_items WHERE cart_id = $1", [cart.rows[0].id]);
return { orders: createdOrders }; }); res.status(201).json({ data: order }); } catch (error) { next(error); } }
