import type {NextFunction,Request,Response} from "express";
import {z} from "zod";
import {query,transaction} from "../config/db.js";
import {HttpError} from "../utils/http-error.js";
const statuses=["pending","accepted","preparing","ready_for_dispatch","completed"] as const;
const transitions:Record<string,string[]>= {pending:["accepted"],accepted:["preparing"],preparing:["ready_for_dispatch"],ready_for_dispatch:["completed"],completed:[]};
export async function buyerOrders(req:Request,res:Response,next:NextFunction){try{const result=await query(`SELECT o.*,COALESCE(json_agg(json_build_object('product_id',i.product_id,'product_name',p.name,'supplier_id',i.supplier_id,'supplier_name',sp.business_name,'quantity',i.quantity,'price_at_order',i.price_at_order)) FILTER(WHERE i.id IS NOT NULL),'[]') items,COALESCE((SELECT json_agg(json_build_object('status',h.status,'updated_at',h.updated_at) ORDER BY h.updated_at) FROM order_status_history h WHERE h.order_id=o.id),'[]') status_history FROM orders o LEFT JOIN order_items i ON i.order_id=o.id LEFT JOIN products p ON p.id=i.product_id LEFT JOIN supplier_profiles sp ON sp.user_id=i.supplier_id WHERE o.buyer_id=$1 GROUP BY o.id ORDER BY o.created_at DESC`,[req.auth!.userId]);res.json({data:result.rows});}catch(error){next(error)}}
export async function supplierOrders(req:Request,res:Response,next:NextFunction){try{const result=await query(`SELECT o.id,o.order_number,o.buyer_id,o.shipping_info,o.status,o.total,o.created_at,COALESCE(json_agg(json_build_object('product_id',i.product_id,'product_name',p.name,'quantity',i.quantity,'price_at_order',i.price_at_order)) FILTER(WHERE i.supplier_id=$1),'[]') items FROM orders o JOIN order_items i ON i.order_id=o.id LEFT JOIN products p ON p.id=i.product_id WHERE i.supplier_id=$1 GROUP BY o.id ORDER BY o.created_at DESC`,[req.auth!.userId]);res.json({data:result.rows});}catch(error){next(error)}}
export async function updateStatus(req:Request,res:Response,next:NextFunction){try{const input=z.object({status:z.enum(statuses)}).parse(req.body);const updated=await transaction(async client=>{const order=await client.query<{id:string;order_number:string;status:string}>(`SELECT o.id,o.order_number,o.status FROM orders o WHERE o.id=$1 AND EXISTS(SELECT 1 FROM order_items i WHERE i.order_id=o.id AND i.supplier_id=$2) FOR UPDATE`,[String(req.params.id),req.auth!.userId]);if(!order.rows[0])throw new HttpError(404,"This order is not assigned to your business");if(!transitions[order.rows[0].status].includes(input.status))throw new HttpError(409,`Orders can move only through Pending → Accepted → Preparing → Ready for Dispatch → Completed`);await client.query("UPDATE orders SET status=$1 WHERE id=$2",[input.status,order.rows[0].id]);await client.query("INSERT INTO order_status_history (order_id,status) VALUES ($1,$2)",[order.rows[0].id,input.status]);return {id:order.rows[0].id,order_number:order.rows[0].order_number,status:input.status};});res.json({data:updated});}catch(error){next(error)}}
