import type {NextFunction,Request,Response} from "express";
import {z} from "zod";import {rfqQuoteSchema,rfqRequestSchema} from "@threadmark/shared";
import {query,transaction} from "../config/db.js";
import {HttpError} from "../utils/http-error.js";
export async function createRfq(req:Request,res:Response,next:NextFunction){try{const input=rfqRequestSchema.parse(req.body);if(input.productId){const p=await query("SELECT p.id FROM products p JOIN supplier_profiles sp ON sp.user_id=p.supplier_id WHERE p.id=$1 AND p.status='available' AND sp.status='approved'",[input.productId]);if(!p.rows[0])throw new HttpError(404,"This product is not available for quote requests");}const created=await query("INSERT INTO rfq_requests (buyer_id,product_id,custom_spec,quantity,target_price,needed_by_date) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id,status,created_at",[req.auth!.userId,input.productId??null,input.customSpec??null,input.quantity,input.targetPrice??null,input.neededByDate??null]);res.status(201).json({data:created.rows[0]});}catch(error){next(error)}}
export async function listBuyerRfqs(req:Request,res:Response,next:NextFunction){try{const result=await query(`SELECT r.id,r.product_id,r.custom_spec,r.quantity,r.target_price,r.needed_by_date,r.status,r.created_at,p.name AS product_name,COALESCE(json_agg(json_build_object('id',q.id,'quoted_price',q.quoted_price,'quoted_lead_time_days',q.quoted_lead_time_days,'notes',q.notes,'status',q.status)) FILTER (WHERE q.id IS NOT NULL),'[]') AS quotes FROM rfq_requests r LEFT JOIN products p ON p.id=r.product_id LEFT JOIN rfq_quotes q ON q.rfq_request_id=r.id WHERE r.buyer_id=$1 GROUP BY r.id,p.name ORDER BY r.created_at DESC`,[req.auth!.userId]);res.json({data:result.rows});}catch(error){next(error)}}
export async function listSupplierRfqs(req:Request,res:Response,next:NextFunction){try{const result=await query(`SELECT r.id,r.product_id,r.custom_spec,r.quantity,r.target_price,r.needed_by_date,r.status,r.created_at,p.name AS product_name FROM rfq_requests r LEFT JOIN products p ON p.id=r.product_id WHERE (p.supplier_id=$1 OR r.product_id IS NULL) AND r.status IN ('open','quoted') ORDER BY r.created_at DESC`,[req.auth!.userId]);res.json({data:result.rows});}catch(error){next(error)}}
export async function quoteRfq(req:Request,res:Response,next:NextFunction){try{const input=rfqQuoteSchema.parse(req.body);const rfq=await query("SELECT r.id,r.product_id,p.supplier_id FROM rfq_requests r LEFT JOIN products p ON p.id=r.product_id WHERE r.id=$1 AND r.status IN ('open','quoted')",[req.params.rfqId]);if(!rfq.rows[0]||(rfq.rows[0].product_id&&rfq.rows[0].supplier_id!==req.auth!.userId))throw new HttpError(404,"This RFQ is not available to quote");const created=await query("INSERT INTO rfq_quotes (rfq_request_id,supplier_id,quoted_price,quoted_lead_time_days,notes) VALUES ($1,$2,$3,$4,$5) RETURNING id,status,created_at",[req.params.rfqId,req.auth!.userId,input.quotedPrice,input.quotedLeadTimeDays,input.notes??null]);await query("UPDATE rfq_requests SET status='quoted' WHERE id=$1",[req.params.rfqId]);res.status(201).json({data:created.rows[0]});}catch(error){next(error)}}
export async function rejectRfq(req:Request,res:Response,next:NextFunction){try{const result=await query(`UPDATE rfq_requests r SET status='rejected' WHERE r.id=$1 AND (r.product_id IS NULL OR EXISTS(SELECT 1 FROM products p WHERE p.id=r.product_id AND p.supplier_id=$2)) AND r.status IN ('open','quoted') RETURNING id,status`,[req.params.rfqId,req.auth!.userId]);if(!result.rows[0])throw new HttpError(404,"This RFQ is not available to reject");res.json({data:result.rows[0]});}catch(error){next(error)}}
export async function decideQuote(req:Request,res:Response,next:NextFunction){try{const decision=z.object({decision:z.enum(["accepted","rejected"])}).parse(req.body);const response=await transaction(async client=>{const quote=await client.query<any>(`SELECT q.*,r.buyer_id,r.quantity,r.status AS request_status FROM rfq_quotes q JOIN rfq_requests r ON r.id=q.rfq_request_id WHERE q.id=$1 FOR UPDATE`,[req.params.quoteId]);if(!quote.rows[0]||quote.rows[0].buyer_id!==req.auth!.userId)throw new HttpError(404,"This quote was not found");await client.query("UPDATE rfq_quotes SET status=$1 WHERE id=$2",[decision.decision,req.params.quoteId]);if(decision.decision==='rejected')return {status:'rejected'};await client.query("UPDATE rfq_requests SET status='accepted' WHERE id=$1",[quote.rows[0].rfq_request_id]);const order=await client.query<{id:string}>("INSERT INTO orders (buyer_id,shipping_info,status,total) VALUES ($1,'{}','pending',$2) RETURNING id",[req.auth!.userId,Number(quote.rows[0].quoted_price)*quote.rows[0].quantity]);await client.query("INSERT INTO order_items (order_id,product_id,supplier_id,quantity,price_at_order) SELECT $1,r.product_id,q.supplier_id,r.quantity,q.quoted_price FROM rfq_requests r JOIN rfq_quotes q ON q.rfq_request_id=r.id WHERE q.id=$2",[order.rows[0].id,req.params.quoteId]);await client.query("INSERT INTO order_status_history (order_id,status) VALUES ($1,'pending')",[order.rows[0].id]);return {status:'accepted',orderId:order.rows[0].id};});res.json({data:response});}catch(error){next(error)}}
