import type {NextFunction,Request,Response} from "express";
import {z} from "zod";import {supplierProductSchema,type SupplierProductInput} from "@threadmark/shared";
import {query,transaction} from "../config/db.js";
import {HttpError} from "../utils/http-error.js";
import {embed} from "../services/huggingface.service.js";
async function saveProduct(client:any,supplierId:string,input:SupplierProductInput,id?:string){const status=input.stockQty===0?'out_of_stock':'available';const embedding=await embed(`${input.name}. ${input.category}. ${input.description}. ${input.composition??""}. ${input.weaveType??""}. ${input.certifications.join(" ")}`);const vector=`[${embedding.join(",")}]`;const args=[input.name,input.category,input.description,input.colors,input.specifications,input.gsm??null,input.composition??null,input.weaveType??null,input.width??null,input.shrinkageRate??null,input.colorfastnessRating??null,input.stockQty,input.stockType,input.leadTimeDays??null,input.certifications,input.price,input.images,status,input.sustainabilityTags,vector];let productId=id;if(id){await client.query(`UPDATE products SET name=$1,category=$2,description=$3,colors=$4,specifications=$5,gsm=$6,composition=$7,weave_type=$8,width=$9,shrinkage_rate=$10,colorfastness_rating=$11,stock_qty=$12,stock_type=$13,lead_time_days=$14,certifications=$15,price=$16,images=$17,status=$18,sustainability_tags=$19,embedding=$20::vector WHERE id=$21 AND supplier_id=$22`,[...args,id,supplierId]);await client.query("DELETE FROM price_tiers WHERE product_id=$1",[id]);}else{const created=await client.query(`INSERT INTO products (supplier_id,name,category,description,colors,specifications,gsm,composition,weave_type,width,shrinkage_rate,colorfastness_rating,stock_qty,stock_type,lead_time_days,certifications,price,images,status,sustainability_tags,embedding) VALUES ($21,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20::vector) RETURNING id`,[...args,supplierId]);productId=created.rows[0].id;}for(const tier of input.priceTiers)await client.query("INSERT INTO price_tiers (product_id,min_qty,price_per_unit) VALUES ($1,$2,$3)",[productId,tier.minQty,tier.pricePerUnit]);return productId;}
export async function listMine(req:Request,res:Response,next:NextFunction){try{const result=await query(`SELECT p.*,COALESCE(json_agg(json_build_object('min_qty',t.min_qty,'price_per_unit',t.price_per_unit)) FILTER(WHERE t.id IS NOT NULL),'[]') price_tiers FROM products p LEFT JOIN price_tiers t ON t.product_id=p.id WHERE p.supplier_id=$1 AND p.status<>'removed' GROUP BY p.id ORDER BY p.id DESC`,[req.auth!.userId]);res.json({data:result.rows});}catch(error){next(error)}}
export async function create(req:Request,res:Response,next:NextFunction){try{const input=supplierProductSchema.parse(req.body);const id=await transaction(client=>saveProduct(client,req.auth!.userId,input));res.status(201).json({data:{id}});}catch(error){next(error)}}
export async function update(req:Request,res:Response,next:NextFunction){try{const input=supplierProductSchema.parse(req.body);const exists=await query("SELECT id FROM products WHERE id=$1 AND supplier_id=$2",[String(req.params.id),req.auth!.userId]);if(!exists.rows[0])throw new HttpError(404,"This product was not found in your catalogue");await transaction(client=>saveProduct(client,req.auth!.userId,input,String(req.params.id)));res.json({data:{id:String(req.params.id)}});}catch(error){next(error)}}
export async function remove(req:Request,res:Response,next:NextFunction){try{const result=await query("UPDATE products SET status='removed' WHERE id=$1 AND supplier_id=$2 RETURNING id",[String(req.params.id),req.auth!.userId]);if(!result.rows[0])throw new HttpError(404,"This product was not found in your catalogue");res.status(204).send();}catch(error){next(error)}}
function cosine(a:number[],b:number[]){let dot=0,ma=0,mb=0;for(let i=0;i<Math.min(a.length,b.length);i++){dot+=a[i]*b[i];ma+=a[i]*a[i];mb+=b[i]*b[i];}return dot/(Math.sqrt(ma)*Math.sqrt(mb)||1);}
export async function suggestCategory(req:Request,res:Response,next:NextFunction){try{const input=z.object({name:z.string().trim().min(2),description:z.string().trim().min(5)}).parse(req.body);const categories=["Apparel fabric", "Home textiles", "Outdoor and performance textiles", "Uniform fabrics", "Technical textiles", "Deadstock fabric"];const source=await embed(`${input.name}. ${input.description}`);const categoryVectors=await Promise.all(categories.map(category=>embed(category)));const ranked=categories.map((category,index)=>({category,score:cosine(source,categoryVectors[index])})).sort((a,b)=>b.score-a.score);res.json({data:{category:ranked[0].category,alternatives:ranked.slice(1,3),method:"hugging-face-embedding-similarity"}});}catch(error){next(error)}}
